
-- Create database
CREATE DATABASE IF NOT EXISTS AURORA_DB;

-- Use database for execution
USE DATABASE AURORA_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;

-- Use RAW schema for ingestion
USE SCHEMA RAW;

-- Define data file format
CREATE OR REPLACE FILE FORMAT csv_ff
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE;
