
-- Create database
CREATE DATABASE IF NOT EXISTS AURORA_DB;

-- Use database for execution
USE DATABASE AURORA_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;

-- Use RAW schema for ingestion
USE SCHEMA RAW;

-- Define data file format
CREATE OR REPLACE FILE FORMAT csv_ff
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE;

-- Create warehouse
CREATE OR REPLACE WAREHOUSE AURORA_WH
WITH 
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;


-- Create storage integration
CREATE OR REPLACE STORAGE INTEGRATION AURORA_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::623897556329:role/aurora-snowflake-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://aurora-raw-okk928/data/');
